using System.ComponentModel.DataAnnotations.Schema;

namespace SampleAPI.Models;

public class AbstractSyncableEntity : AbstractEntity
{
    // TODO: make it autogenerated on Compute (find the max value in db then increment and set)
    [Column("sync_version")]
    public long SyncVersion { get; set; }
}